---
- name: Creating Infrastructure
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - config.yml
  tasks:
  - include: create_network_infrastructure.yml
    tags: networks
    vars:
    - AMBARI_SERVER: 1
    - EDGENODE: 1
    - NAMENODE: 1
    - SNAMENODE: 1
    - DATANODE: 5
  - include: create_instances.yml
    tags: instances

