---
- name: Prepare instances
  hosts: all
  remote_user: cloud-user
  become: true
  tasks:
  - include: tasks/prepare_instance.yml
  tags: environment

- name: Install Ambari Server
  hosts: all
  remote_user: cloud-user
  become: true
  tags: ambari
  any_errors_fatal: true
  roles:
    - role: ambari
      vars:
      - AMBARI_REPO: "http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.5.0.3/ambari.repo"

- name: Deploy blueprint and Cluster configuration
  hosts: localhost
  tags: blueprint
  any_errors_fatal: true
  roles:
    - role: blueprints
      vars:
      - ACTION: DEPLOY
#      - AMBARI_HOST: "{% for host in groups['ambari'] %}{{ hostvars['host']['facter_ec2_metadata']['public-ipv4'] | to_nice_yaml }}{% endfor %}"
      - AMBARI_HOST: 10.95.250.70
      - AMBARI_USER: admin
      - AMBARI_PASS: admin
      - AMBARI_blueprintname: DOPG
      - AMBARI_blueprintfile: blueprint.json.j2
      - AMBARI_blueprintfile_type: file
      - AMBARI_clustername: DSN
      - AMBARI_clusterfile: cluster.json.j2
      - AMBARI_clusterfile_type: template
      - AMBARI_SERVER: 1
      - EDGENODE: 1
      - NAMENODE: 1
      - SNAMENODE: 1
      - DATANODE: 5
