---
- name: Prepare instances
  hosts: all
  remote_user: cloud-user
  become: true
  tasks:
  - include: tasks/prepare_instance.yml
  tags: environment

- name: Install Ambari Server
  hosts: all
  remote_user: cloud-user
  become: true
  tags: ambari
  any_errors_fatal: true
  roles:
    - role: ambari
      vars:
      - AMBARI_REPO: "http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.5.0.3/ambari.repo"

- name: Deploy blueprint and Cluster configuration
  hosts: localhost
  gather_facts: true
  tags: blueprint
  any_errors_fatal: true
  vars_files:
    - cluster.yml
  roles:
    - role: blueprints
      vars:
      - ACTION: DEPLOY
      - AMBARI_HOST: '{{ hostvars[groups[ambari][0]].[facter_ec2_metadata].[public-ipv4] }}'
#      - AMBARI_HOST: 10.95.251.229
      - AMBARI_USER: admin
      - AMBARI_PASS: admin
      - AMBARI_blueprintname: DOPG
      - AMBARI_blueprintfile: blueprint.json.j2
      - AMBARI_clustername: DSN
      - AMBARI_clusterfile: cluster.json.j2