- name: Delete {{ AMBARI_blueprintname }} blueprint from Ambari Server
  uri:
    url: http://{{ AMBARI_HOST }}:8080/api/v1/blueprints/{{ AMBARI_blueprintname }}
    method: DELETE
    HEADER_X-Requested-By: "ambari"
    user: '{{ AMBARI_USER }}'
    password: '{{ AMBARI_PASS }}'
    force_basic_auth: yes
    status_code: 200